# Generated by Django 3.1.1 on 2020-09-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler_story', '0002_auto_20200920_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='The_loai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_loai', models.CharField(max_length=15)),
            ],
        ),
        migrations.RenameField(
            model_name='chaper',
            old_name='content',
            new_name='noi_dung',
        ),
        migrations.RenameField(
            model_name='chaper',
            old_name='name_chap',
            new_name='ten_chap',
        ),
        migrations.CreateModel(
            name='Truyen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_truyen', models.CharField(max_length=50)),
                ('trang_thai', models.CharField(max_length=15)),
                ('tac_gia', models.CharField(max_length=30)),
                ('dan_truyen', models.TextField()),
                ('the_loai', models.ManyToManyField(to='crawler_story.The_loai')),
            ],
        ),
    ]
