# Generated by Django 3.1.1 on 2020-09-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler_story', '0003_auto_20200923_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='the_loai',
            options={'ordering': ['the_loai']},
        ),
        migrations.AlterModelOptions(
            name='truyen',
            options={'ordering': ['ten_truyen']},
        ),
        migrations.AlterField(
            model_name='the_loai',
            name='the_loai',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
