# Generated by Django 3.1.1 on 2020-09-25 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler_story', '0004_auto_20200925_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaper',
            name='ten_truyen',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='crawler_story.truyen'),
            preserve_default=False,
        ),
    ]
