# Generated by Django 3.1.1 on 2020-09-27 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler_story', '0005_chaper_ten_truyen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='the_loai',
            options={},
        ),
        migrations.AlterModelOptions(
            name='truyen',
            options={},
        ),
    ]
