# Generated by Django 3.1.1 on 2020-09-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler_story', '0007_auto_20200929_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thể_loại',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
