# Generated by Django 3.1.1 on 2020-09-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler_story', '0008_auto_20200929_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaper',
            name='name_story',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='chaper',
            name='tac_gia',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
